/*-- MySQL Script generated by MySQL Workbench
-- Correções aplicadas
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ifspStoreBD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `IFSPStoreBD` DEFAULT CHARACTER SET utf8;
USE `IFSPStoreBD`;

-- -----------------------------------------------------
-- Table `Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IFSPStoreBD`.`Usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NULL,
  `Senha` VARCHAR(45) NULL,
  `Login` VARCHAR(45) NULL,
  `DataCadastro` TIMESTAMP NULL,
  `DataLogin` TIMESTAMP NULL,
  `Ativo` BINARY NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IFSPStoreBD`.`Grupo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IFSPStoreBD`.`Produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NULL,
  `Preco` DECIMAL(10,2) NULL,
  `Quantidade` INT NULL,
  `DataCompra` DATE NULL,
  `UnidadeVenda` VARCHAR(10) NULL,
  `idGrupo` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Produto_Grupo_idx` (`idGrupo` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_Grupo`
    FOREIGN KEY (`idGrupo`)
    REFERENCES `IFSPStoreBD`.`Grupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IFSPStoreBD`.`Cidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NULL,
  `Estado` VARCHAR(2) NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IFSPStoreBD`.`Cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NULL,
  `Endereco` VARCHAR(100) NULL,
  `Documento` VARCHAR(45) NULL,
  `Bairro` VARCHAR(45) NULL,
  `Cidade` VARCHAR(45) NULL,
  `idCidade` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Cliente_Cidade1_idx` (`idCidade` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Cidade1`
    FOREIGN KEY (`idCidade`)
    REFERENCES `IFSPStoreBD`.`Cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IFSPStoreBD`.`Venda` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Data` TIMESTAMP NULL,
  `ValorTotal` DECIMAL(10,2) NULL,
  `idCliente` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Venda_Cliente1_idx` (`idCliente` ASC) VISIBLE,
  INDEX `fk_Venda_Usuario1_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Venda_Cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `IFSPStoreBD`.`Cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `IFSPStoreBD`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `VendaItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IFSPStoreBD`.`VendaItem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Quantidade` INT NULL,
  `ValorUnitario` DECIMAL(10,2) NULL,
  `ValorTotal` DECIMAL(10,2) NULL,
  `idVenda` INT NOT NULL,
  `idProduto` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_VendaItem_Venda1_idx` (`idVenda` ASC) VISIBLE,
  INDEX `fk_VendaItem_Produto1_idx` (`idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_VendaItem_Venda1`
    FOREIGN KEY (`idVenda`)
    REFERENCES `IFSPStoreBD`.`Venda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VendaItem_Produto1`
    FOREIGN KEY (`idProduto`)
    REFERENCES `IFSPStoreBD`.`Produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;*/
